# Generated by Django 3.2.12 on 2022-07-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='Welcome*123', max_length=15),
        ),
    ]
