# Generated by Django 3.2.12 on 2022-07-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0005_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(default=models.CharField(max_length=30), max_length=15),
        ),
    ]
