# Generated by Django 3.2.12 on 2022-07-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0006_employee_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=15),
        ),
    ]
